// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqIsIojD7TnCNCIdLDnahL4zFm7igM2ls',
    appId: '1:238699465497:web:555b592238f96ef3ba1388',
    messagingSenderId: '238699465497',
    projectId: 'seniorcareapp-b64f3',
    authDomain: 'seniorcareapp-b64f3.firebaseapp.com',
    storageBucket: 'seniorcareapp-b64f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZHxHiN4nWrmZPXuNHnwnwivqj32ET2JQ',
    appId: '1:238699465497:android:50f08fc33d1dab17ba1388',
    messagingSenderId: '238699465497',
    projectId: 'seniorcareapp-b64f3',
    storageBucket: 'seniorcareapp-b64f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtad4UhSQkLGAegB5-QGyx2oOPrfME67g',
    appId: '1:238699465497:ios:2ffef0f86e02ac05ba1388',
    messagingSenderId: '238699465497',
    projectId: 'seniorcareapp-b64f3',
    storageBucket: 'seniorcareapp-b64f3.firebasestorage.app',
    iosBundleId: 'com.example.seniorcareapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtad4UhSQkLGAegB5-QGyx2oOPrfME67g',
    appId: '1:238699465497:ios:2ffef0f86e02ac05ba1388',
    messagingSenderId: '238699465497',
    projectId: 'seniorcareapp-b64f3',
    storageBucket: 'seniorcareapp-b64f3.firebasestorage.app',
    iosBundleId: 'com.example.seniorcareapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqIsIojD7TnCNCIdLDnahL4zFm7igM2ls',
    appId: '1:238699465497:web:3434baff9e7ae566ba1388',
    messagingSenderId: '238699465497',
    projectId: 'seniorcareapp-b64f3',
    authDomain: 'seniorcareapp-b64f3.firebaseapp.com',
    storageBucket: 'seniorcareapp-b64f3.firebasestorage.app',
  );
}
